language: python
python: 3.4

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pyparsing1
  - TOXENV=flask08
  - TOXENV=flask09
  - TOXENV=coverage
  - TOXENV=lint
  - TOXENV=docs

before_install:
  - sudo apt-get -y install libcairo2-dev

install:
  - pip install tox

script: "./.travis.sh"

matrix:
  allow_failures:
    - env: TOXENV=coverage
